spring :
  application:
    name : toypjt-v.1.0.0

  datasource:
    url : jdbc:mysql://database-1.cn8mi28maccx.ap-northeast-2.rds.amazonaws.com:3306/toypjt?useSSL=false&serverTimezone=UTC
    username : admin
    password : rlaxogns1!
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa :
    hibernate:
      ddl-auto : update
    show-sql : true

  thymeleaf:
    cache: false  # 캐시 비활성화
    mode: LEGACYHTML5
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  mvc :
    view :
      prefix: classpath:/templates/
      suffix: .html
  jsp :
    enabled : false

logging :
  level :
    org :
      springframework :
        security : DEBUG
